### ISSUE TITLE
Music event "requester" not working

### ISSUE THREAD

**Issue by arionukshini** [Koenie06/Discord.js-Music#18]
When I use the requester thing for like `Requested by ${requester.tag}`
I get this error 
`TypeError: Cannot read properties of undefined (reading 'tag')
    at EventEmitter.<anonymous> (/home/runner/Harmony-Beta/events/musicEvents.js:26:40)
    at EventEmitter.emit (node:events:390:28)
    at Object.exports.play (/home/runner/Harmony-Beta/node_modules/@koenie06/discord.js-music/src/index.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`
and when i try to log it it just says undefined

**Comment by Koenie06** [comment]
Have you provided a valid Interaction Class into the .play() function?

**Comment by arionukshini** [comment]
ye i did i added message cus i was doing normal cmds
